export const profile = {
    name: "Shogbola Rotimi",
    role: "Web Developer & Computer Scientist",
    location: "Lagos, Nigeria",
    email: "Rotisho@gmail.com",
    phone: "+234 811 862 7214",
    degree: "B.Sc Computer Science, Babcock University",
    available: true,
    intro: "Web developer and QA engineer based in Lagos. I care about software that's not just functional, but reliable and well-designed.",
    about: "A passionate and versatile developer specializing in Information Systems, with strong skills in web development, programming, and mobile application design. I build responsive websites across different industries and work as a quality assurance engineer, making sure the products I help create are reliable, performant, and genuinely enjoyable to use. I care deeply about problem-solving, clean architecture, and interfaces that feel effortless, and I'm committed to continuous learning, innovation, and teamwork.",
    marquee: ["Interfaces", "Mobile Apps", "Systems", "Problem Solving"],
};

export const projects = [{
        id: "01",
        title: "ICFA Worldwide",
        subtitle: "International Centre for Family Advancement",
        description: "A nonprofit platform for a family-advancement organization — outreach programs, impact stories, volunteer onboarding, donations and an integrated shop.",
        tags: ["Nonprofit", "Web", "E-commerce"],
        year: "2025",
        url: "https://www.icfaworldwide.net",
        image: "",
    },
    {
        id: "02",
        title: "Konibaje.100",
        subtitle: "Brand & event experience",
        description: "An interactive, motion-driven web experience built for the Konibaje 100 brand.",
        tags: ["Web", "Motion", "Brand"],
        year: "2024",
        url: "https://www.konibaje100.com",
        image: "",
    },
    {
        id: "03",
        title: "PMC Inspires",
        subtitle: "Leadership & community platform",
        description: "A platform for a leadership, entrepreneurship, and faith-driven community — featuring a content hub, published books, an integrated shop, events, and testimonials.",
        tags: ["Community", "Web", "E-commerce"],
        year: "2025",
        url: "https://www.pmccollective.com",
        image: "",
    },
    {
        id: "04",
        title: "E-Invoicing Middleware Platform",
        subtitle: "FIRS / NRS invoicing platform",
        description: "A multi-tenant platform that lets companies generate, validate and submit invoices to Nigeria's FIRS via the National Reporting System. Built the front-end interfaces and handled QA — test planning, API testing, and NRS schema validation.",
        tags: ["Frontend", "React", "QA"],
        year: "2026",
        url: "#",
        image: "",
    },
    {
        id: "05",
        title: "Asset Management System",
        subtitle: "Internal staff & equipment tracking",
        description: "An internal tool for tracking company staff and equipment. Helped build the interface with React and Tailwind CSS and handled quality assurance to keep it reliable and accurate in daily use.",
        tags: ["React", "Tailwind", "QA"],
        year: "2026",
        url: "#",
        image: "",
    },
    {
        id: "06",
        title: "iTransit",
        subtitle: "Transit management platform",
        description: "A company transit management platform. Built responsive front-end interfaces and handled quality assurance to keep the product reliable across its core flows.",
        tags: ["Frontend", "React", "QA"],
        year: "2025",
        url: "#",
        image: "",
    },
    // ── ADD MORE: copy a block above, change the fields ──
];

export const experience = [{
        role: "SWIFT Platform Analyst",
        org: "Telnet Nigeria Limited",
        year: "2026",
        points: [
            "Support upgrades of the SWIFT Alliance messaging platform and its web interface.",
            "Maintain and upgrade SNL (SWIFTNet Link) connectivity paths.",
            "Work alongside the software and QA teams on secure financial-messaging infrastructure.",
        ],
    },
    {
        role: "FRONTEND DEVELOPER & QUALITY ASSURANCE ENGINEER",
        org: "Telnet Nigeria Limited",
        year: "2026",
        points: [
            "Created responsive, user-friendly web interfaces using React and Tailwind CSS.",
            "Tested and debugged applications to ensure optimal performance and user experience.",
            "Created and maintained documentation for code, testing procedures, and best practices.",
        ],
    },
    {
        role: "Intern — Corporate Planning & Strategy",
        org: "NITDA (National Information Technology Development Agency)",
        year: "Jan – Jun 2023",
        points: [
            "Assisted in strategic planning and corporate research.",
            "Supported data collection, analysis, and reporting for the CPS department.",
            "Contributed to ICT policy implementation and org development projects.",
        ],
    },
];

export const skills = [
    "Next.js",
    "CSS",
    "Tailwind CSS",
    "JavaScript",
    "TypeScript",
    "React",
    "Framer Motion",
    "HTML",
    "Git",
    "Flutter / Dart",
    "Firebase",
];